##############################################
############## Core Services #################
##############################################
services:
  config-server:
    build:
      context: . # Root project dir
      dockerfile: config-server/Dockerfile
    container_name: config-server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8888:8888
    networks:
      - my_app_network

  discovery-service:
    build:
      context: . # Root project dir
      dockerfile: discovery-service/Dockerfile
    container_name: discovery-service
    restart: unless-stopped
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-service:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761
    networks:
      - my_app_network

  service-a:
    build:
      context: . # Root project dir
      dockerfile: service-a/Dockerfile
    container_name: service-a
    restart: unless-stopped
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://service-a:8081/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - 8081:8081
    networks:
      - my_app_network

  service-b:
    build:
      context: . # Root project dir
      dockerfile: service-b/Dockerfile
    container_name: service-b
    restart: unless-stopped
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://service-b:8082/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - my_app_network

  gateway-service:
    build:
      context: . # Root project dir
      dockerfile: gateway-service/Dockerfile
    container_name: gateway-service
    restart: unless-stopped
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://gateway-service:8989/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      service-a:
        condition: service_healthy
      service-b:
        condition: service_healthy
    ports:
      - 8989:8989
    networks:
      - my_app_network

##############################################
##############################################

networks:
  my_app_network:
    driver: bridge
